---
apiVersion: v1
kind: Namespace
metadata:
  name: position-size
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-size-deploy
  namespace: position-size
  labels:
    app: position-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-app
  template:
    metadata:
      labels:
        app: position-app
    spec:
      containers:
        - name: positionsize
          image: docker.io/jsanderson104/stuff:position_size-v1
          ports:
            - containerPort: 80
              name: web-80
---
apiVersion: v1
kind: Service
metadata:
  name: positionsize-loadbalancer
  namespace: position-size
  labels:
    app: position-app
spec:
  type: LoadBalancer
  selector:
    app: position-app
  ports:
    - name: web-80
      protocol: TCP
      port: 80
      targetPort: 80
